main = "src/index.ts"
name = "blogging"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNzFmOTk3NjQtZWI3My00MzlhLWJhZTQtNmVmMTUzYTk4NWU3IiwidGVuYW50X2lkIjoiMDQ0NmNjMzIyNGJiM2NjN2E2ODMxNzNiYzEyZTZlNjk1MWY4YTg1NmRkODRjMzNkOGEzODdlNmNkNDNlMjcxOCIsImludGVybmFsX3NlY3JldCI6IjZmYzI1NzdkLTcyY2UtNGRlZC04NjVlLTljZDg1ZTVlYmE5MCJ9.ns2yiohJPQO6tWuCtFGlY1vvitQ5Z7Ztpy2liwrAOcQ"
JWT_SECRET = "secret"
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
